"""initial canonical schema

Revision ID: e25b2d963ce4
Revises:
Create Date: 2026-08-11 22:11:48.542504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e25b2d963ce4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
    )
    op.create_index(op.f("ix_games_slug"), "games", ["slug"], unique=True)
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("progression", "useful", "filler", "trap", name="itemclassification"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("upstream_url", sa.String(length=512), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_items_game_id_games")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("game_id", "name", name="uq_item_game_name"),
    )
    op.create_index(op.f("ix_items_game_id"), "items", ["game_id"], unique=False)
    op.create_index(op.f("ix_items_source"), "items", ["source"], unique=False)
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_start", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("upstream_url", sa.String(length=512), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_regions_game_id_games")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("game_id", "name", name="uq_region_game_name"),
    )
    op.create_index(op.f("ix_regions_game_id"), "regions", ["game_id"], unique=False)
    op.create_index(op.f("ix_regions_source"), "regions", ["source"], unique=False)
    op.create_table(
        "entrances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("from_region_id", sa.Integer(), nullable=False),
        sa.Column("to_region_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_confidence", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("upstream_url", sa.String(length=512), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_region_id"], ["regions.id"], name=op.f("fk_entrances_from_region_id_regions")
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_entrances_game_id_games")),
        sa.ForeignKeyConstraint(
            ["to_region_id"], ["regions.id"], name=op.f("fk_entrances_to_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entrances")),
    )
    op.create_index(
        "ix_entrance_from_to", "entrances", ["from_region_id", "to_region_id"], unique=False
    )
    op.create_index(op.f("ix_entrances_game_id"), "entrances", ["game_id"], unique=False)
    op.create_index(op.f("ix_entrances_source"), "entrances", ["source"], unique=False)
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_confidence", sa.Float(), nullable=False),
        sa.Column("vanilla_item_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("license", sa.String(length=64), nullable=False),
        sa.Column("upstream_url", sa.String(length=512), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], name=op.f("fk_locations_game_id_games")),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_locations_region_id_regions")
        ),
        sa.ForeignKeyConstraint(
            ["vanilla_item_id"], ["items.id"], name=op.f("fk_locations_vanilla_item_id_items")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("game_id", "name", name="uq_location_game_name"),
    )
    op.create_index(op.f("ix_locations_game_id"), "locations", ["game_id"], unique=False)
    op.create_index(op.f("ix_locations_region_id"), "locations", ["region_id"], unique=False)
    op.create_index(op.f("ix_locations_source"), "locations", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_source"), table_name="locations")
    op.drop_index(op.f("ix_locations_region_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_game_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_entrances_source"), table_name="entrances")
    op.drop_index(op.f("ix_entrances_game_id"), table_name="entrances")
    op.drop_index("ix_entrance_from_to", table_name="entrances")
    op.drop_table("entrances")
    op.drop_index(op.f("ix_regions_source"), table_name="regions")
    op.drop_index(op.f("ix_regions_game_id"), table_name="regions")
    op.drop_table("regions")
    op.drop_index(op.f("ix_items_source"), table_name="items")
    op.drop_index(op.f("ix_items_game_id"), table_name="items")
    op.drop_table("items")
    op.drop_index(op.f("ix_games_slug"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###

    # create_table() emitted CREATE TYPE for the native enum, but drop_table()
    # does not emit the matching DROP TYPE. Without this the type outlives the
    # downgrade and the next upgrade fails with "type itemclassification already
    # exists". Autogenerate never writes this line; it has to be maintained by
    # hand for every native enum.
    sa.Enum(name="itemclassification").drop(op.get_bind(), checkfirst=True)
